### PR TITLE
stdin works now

### LINKED ISSUE #1: quit command not working
This is a great project. I searched for a solution to redirect the input/output of the game. And The output works great. But when I write "quit" nothing happens.
How can I stop the server?

### PR DESCRIPTION
**Pull request by JJBlue**
- Stdin works now
- import the new pty client
- removed the io.copy error message

Fixes #1

### CODE REVIEW

**Comment by JJBlue** [comment]
Fixes #1

**Comment by lukbukkit** [comment]
Thanks for your pull request. I tested it on my server and it works fine, but I guess we can't emulate the whole (native) experience of just using `srcds_linux`, like auto-completion or the command history via arrow keys.
So my question is, how are you using the `source_logger`. Are you redirecting the output to a file, are you using it with `systemd` or are you using your own software?

**Comment by JJBlue** [comment]
( I'm from Germany. I hope you my english is not so bad :) )
I have wrote a Java Client/Server Programm in which I can run a lot of "small servers" and control them. I can also see in my Java Programm the Output of the Server and send them via the Input commands to them.
 
So I start with the Java "BuilderProcess" with the arguements "./source_logger …"
And with the Little Change from me (I compiled it before, I send you the request). It works very well.
 
If you have more Questions, write me back.

-----Ursprüngliche Nachricht-----Von: Lukas <notifications@github.com>Gesendet: Samstag, 21. März 2020 18:40An: LukWebsForge/SourceLogger <sourcelogger@noreply.github.com>Cc: JJBlue <lieb.julian@gmx.de>; Author <author@noreply.github.com>Betreff: Re: [LukWebsForge/SourceLogger] stdin works now (#2)</author@noreply.github.com></lieb.julian@gmx.de></sourcelogger@noreply.github.com>


 
Thanks for your pull request. I tested it on my server and it works fine, but I guess we can't emulate the whole (nativ) experience of just using srcds_linux, like auto-completion or the command history via arrow keys.So my question is, how are you using the source_logger. Are you redirecting the output to a file, are you using it with systemd or are you using your own software?

**Comment by lukbukkit** [comment]
Yeah that seems to be a very useful use case. Thanks for your clarification. I'll merge your pull request, and also thanks for your work and good luck with your project. 👍

**Pull request merged**
